### ISSUE TITLE
Command-line plot needs to be flexible on time dimension

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#184]
```pytb
Traceback (most recent call last):
  File "notebooks/Command_Line_Tools/synopticplot.py", line 160, in <module>
    gfs_time, gfs_lat_grid, gfs_lon_grid, gfs_data_grid = get_closest_gfs(requested_time, args.gfslevel, args.gfsfield)
  File "notebooks/Command_Line_Tools/synopticplot.py", line 48, in get_closest_gfs
    time_var = data.variables['reftime1']
KeyError: 'reftime1'
```
So you need to actually look in the `coordinates` attribute. Because of course we no sooner get things green and they break again. I hate live data.

**Comment by dopplershift** [comment]
Fixed in #185.
